import Layout from '@/utils/Layout/Layout';
import HomePage from '@/views/features/Home/Home';

export default function Home({ mainData }: { mainData: any }) {
  return (
    <Layout title='Test task by Hoo.be' description='Generated by test task' bodyClass='home'>
      <HomePage data={mainData} />
    </Layout>
  )
}

export async function getServerSideProps() {
  try {
    const mainRes = await fetch(
      `${process?.env?.NEXT_PUBLIC_API_PORT}api/test-data.json`,
      {
        method: "GET",
        headers: {
          "Access-Control-Allow-Origin": "*",
          Accept: "application/json",
          mode: "no-cors",
        },
      }
    );
    const mainData = await mainRes.json();

    return {
      props: {
        mainData,
      },
    };
  } catch (error) {
    console.error(error);
    return { props: {} };
  }
}

